name: Deploy to Production

on:
  push:
    branches: [ v2 ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          # Disable strict host key checking
          echo -e "Host *\n\tStrictHostKeyChecking no\n\t" > ~/.ssh/config
          
          rsync -avz -e "ssh -i ~/.ssh/deploy_key" --delete \
            --exclude='.git*' \
            --exclude='node_modules' \
            --exclude='.env' \
            ./ root@$HOST:/var/www/kymera.cloud/

          ssh -i ~/.ssh/deploy_key root@$HOST << 'ENDSSH'
            cd /var/www/kymera.cloud
            export NODE_ENV=production
            npm install
            npm run build
            systemctl restart kymera
            sleep 2
            systemctl status kymera
          ENDSSH